BÀI 1

In [53]:
import torch

a = torch.tensor(
    [[1, 2, 3],
     [4, 5, 6]],
    dtype=torch.int32
)

print(a)
print("Kích thước:", a.shape)
print("Số chiều:", a.ndim)
print("Kiểu dữ liệu:", a.dtype)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)
Kích thước: torch.Size([2, 3])
Số chiều: 2
Kiểu dữ liệu: torch.int32


BÀI 2

In [5]:
import torch

a = torch.rand(3, 4)
b = torch.randn(3, 4)
c = torch.zeros(2, 3)
d = torch.ones(2, 3)
e = torch.eye(4)

print("Tensor rand:")
print(a)

print("\nTensor randn:")
print(b)

print("\nTensor zeros:")
print(c)

print("\nTensor ones:")
print(d)

print("\nMa trận đơn vị:")
print(e)

f = torch.full((5, 5), 10)

print("\nTensor 5 × 5 toàn giá trị 10:")
print(f)

Tensor rand:
tensor([[0.1945, 0.9861, 0.3331, 0.5770],
        [0.8633, 0.9727, 0.5488, 0.6050],
        [0.7462, 0.7574, 0.0599, 0.3362]])

Tensor randn:
tensor([[ 1.4415, -0.0143,  1.0897, -2.3454],
        [ 0.4322, -0.9803,  1.5898,  0.5910],
        [ 1.1763, -0.2454,  0.3381, -0.1512]])

Tensor zeros:
tensor([[0., 0., 0.],
        [0., 0., 0.]])

Tensor ones:
tensor([[1., 1., 1.],
        [1., 1., 1.]])

Ma trận đơn vị:
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

Tensor 5 × 5 toàn giá trị 10:
tensor([[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]])


BÀI 3

In [34]:
import torch

a = torch.zeros(2, 3, 4)

print("Tensor:")
print(a)

print("Shape:", a.shape)
print("Size:", a.size())
print("Number of dimensions:", a.ndim)
print("Data type:", a.dtype)

Tensor:
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
Shape: torch.Size([2, 3, 4])
Size: torch.Size([2, 3, 4])
Number of dimensions: 3
Data type: torch.float32


BÀI 4

In [33]:
import torch

a = torch.randn(3, 4, 5)

print("Original tensor:")
print(a)

print("\nTensor a[1]:")
print(a[1])

print("\nTensor a[1:, 2:4]:")
print(a[1:, 2:4])

print("\nShape của a[1]:")
print(a[1].shape)

print("\nShape của a[1:, 2:4]:")
print(a[1:, 2:4].shape)

print("\nHai phần tử cuối cùng trên chiều thứ ba:")
print(a[:, :, -2:])

Original tensor:
tensor([[[ 0.1706,  0.0179, -0.9613,  0.8406,  0.0539],
         [-1.3022,  1.3570,  0.1206,  1.1868, -1.5935],
         [ 2.0071,  0.2658,  1.1042,  0.7600,  1.0443],
         [ 1.3932, -1.1304,  0.3488,  0.5485, -0.3110]],

        [[-0.0040, -0.9675,  0.4354, -0.2696,  0.5646],
         [ 0.3090, -0.2912,  0.3155,  2.1656,  1.0142],
         [ 0.4102, -0.0843,  0.4003, -1.5548,  1.2092],
         [-1.0604, -0.2695,  0.5667,  2.3960,  0.3178]],

        [[-0.5984,  1.2989,  0.3704,  1.5404, -0.6996],
         [-1.0508,  0.1272, -1.2161,  0.1528,  0.6691],
         [-0.5112, -0.2519,  0.5282, -0.7301,  1.7164],
         [-0.2048, -1.7002,  0.7964,  0.2788,  0.1161]]])

Tensor a[1]:
tensor([[-0.0040, -0.9675,  0.4354, -0.2696,  0.5646],
        [ 0.3090, -0.2912,  0.3155,  2.1656,  1.0142],
        [ 0.4102, -0.0843,  0.4003, -1.5548,  1.2092],
        [-1.0604, -0.2695,  0.5667,  2.3960,  0.3178]])

Tensor a[1:, 2:4]:
tensor([[[ 0.4102, -0.0843,  0.4003, -1.5548,  1.2

BÀI 5

In [19]:
import torch

a = torch.randn(3, 4)

print("Original:")
print(a)

print("\nSố phần tử ban đầu:")
print(a.numel())

print("\nFlatten:")
print(a.ravel())

print("\nReshape to 3 x 2 x 2:")
print(a.reshape(3, 2, 2))

print("\nReshape to 2 x 6:")
print(a.reshape(2, 6))

print("\nSố phần tử sau reshape:")
print(a.reshape(2, 6).numel())

Original:
tensor([[-1.3430, -0.4206,  1.8643,  0.7278],
        [ 0.8543,  0.9006, -0.8571,  1.7412],
        [ 0.3872,  0.2138,  0.4557,  1.0906]])

Số phần tử ban đầu:
12

Flatten:
tensor([-1.3430, -0.4206,  1.8643,  0.7278,  0.8543,  0.9006, -0.8571,  1.7412,
         0.3872,  0.2138,  0.4557,  1.0906])

Reshape to 3 x 2 x 2:
tensor([[[-1.3430, -0.4206],
         [ 1.8643,  0.7278]],

        [[ 0.8543,  0.9006],
         [-0.8571,  1.7412]],

        [[ 0.3872,  0.2138],
         [ 0.4557,  1.0906]]])

Reshape to 2 x 6:
tensor([[-1.3430, -0.4206,  1.8643,  0.7278,  0.8543,  0.9006],
        [-0.8571,  1.7412,  0.3872,  0.2138,  0.4557,  1.0906]])

Số phần tử sau reshape:
12


BÀI 6

In [36]:
import torch

a = torch.randn(2, 3)
b = torch.randn(2, 3)

print("a:")
print(a)

print("\nb:")
print(b)

print("\na + b:")
print(a + b)

print("\na / b:")
print(a / b)

print("\na^2:")
print(a ** 2)

print("\na * b:")
print(a * b)

print("\nMatrix multiplication:")
print(a @ b.T)

print("\nShape của a @ b.T:")
print((a @ b.T).shape)

a:
tensor([[ 0.3789, -0.3182, -2.8467],
        [ 1.5288, -0.7911, -0.7964]])

b:
tensor([[ 1.9047, -0.2348,  0.4364],
        [ 2.5594,  0.1566,  0.0162]])

a + b:
tensor([[ 2.2835, -0.5530, -2.4103],
        [ 4.0882, -0.6345, -0.7802]])

a / b:
tensor([[  0.1989,   1.3555,  -6.5236],
        [  0.5973,  -5.0506, -49.1696]])

a^2:
tensor([[0.1435, 0.1013, 8.1036],
        [2.3371, 0.6259, 0.6343]])

a * b:
tensor([[ 0.7216,  0.0747, -1.2422],
        [ 3.9128, -0.1239, -0.0129]])

Matrix multiplication:
tensor([[-0.4459,  0.8737],
        [ 2.7500,  3.7760]])

Shape của a @ b.T:
torch.Size([2, 2])


BÀI 7

In [35]:
import torch

a = torch.randn(3, 4)

print(a)

print("\nMean:")
print(torch.mean(a, dim=0))

print("\nStandard deviation:")
print(torch.std(a, dim=0))

print("\nCumulative sum:")
print(torch.cumsum(a, dim=0))


print("\nMean:")
print(torch.mean(a, dim=1))

print("\nStandard deviation:")
print(torch.std(a, dim=1))

print("\nCumulative sum:")
print(torch.cumsum(a, dim=1))

tensor([[ 0.7545,  0.7043, -0.0409,  0.9249],
        [ 2.1667, -1.8438, -1.1086,  0.0462],
        [-1.1178, -0.1414, -1.0205, -0.2950]])

Mean:
tensor([ 0.6011, -0.4270, -0.7233,  0.2254])

Standard deviation:
tensor([1.6476, 1.2978, 0.5926, 0.6293])

Cumulative sum:
tensor([[ 0.7545,  0.7043, -0.0409,  0.9249],
        [ 2.9213, -1.1396, -1.1496,  0.9711],
        [ 1.8034, -1.2810, -2.1700,  0.6761]])

Mean:
tensor([ 0.5857, -0.1849, -0.6437])

Standard deviation:
tensor([0.4283, 1.7501, 0.4969])

Cumulative sum:
tensor([[ 0.7545,  1.4588,  1.4178,  2.3427],
        [ 2.1667,  0.3229, -0.7857, -0.7395],
        [-1.1178, -1.2592, -2.2797, -2.5746]])


BÀI 8

In [40]:
import torch

x = torch.tensor(
    3.6,
    requires_grad=True
)

y = x * x

y.backward()

print("x =", x)
print("y =", y)
print("x.grad =", x.grad)

manual_gradient = 2 * 3.6

print("\nĐạo hàm thủ công =", manual_gradient)
print("Gradient bằng Autograd =", x.grad)

x = torch.tensor(
    3.6,
    requires_grad=True
)

y = 3 * x**2 + 2 * x + 1

y.backward()

print("\nx =", x)
print("y =", y)
print("x.grad =", x.grad)

x = tensor(3.6000, requires_grad=True)
y = tensor(12.9600, grad_fn=<MulBackward0>)
x.grad = tensor(7.2000)

Đạo hàm thủ công = 7.2
Gradient bằng Autograd = tensor(7.2000)

x = tensor(3.6000, requires_grad=True)
y = tensor(47.0800, grad_fn=<AddBackward0>)
x.grad = tensor(23.6000)


BÀI 9

In [3]:
import numpy as np
import torch

polynomial = np.poly1d([1, 2, 3])
N = 20
X = np.random.randn(N, 1) * 5
Y = polynomial(X)

XX = np.hstack([
    X * X,
    X,
    np.ones_like(X)
])
w = torch.randn(3, 1, requires_grad=True)
x = torch.tensor(XX, dtype=torch.float32)
y = torch.tensor(Y, dtype=torch.float32)
optimizer = torch.optim.NAdam([w], lr=0.01)
print("Initial coefficients:")
print(w)

for epoch in range(1000):
    optimizer.zero_grad()
    y_pred = x @ w
    mse = torch.mean(torch.square(y - y_pred))
    mse.backward()
    optimizer.step()
print("Learned coefficients:")
print(w)

print("\n===== YÊU CẦU 1 =====")

correct = torch.tensor([
    [1.0],
    [2.0],
    [3.0]
])

print("Hệ số học được:")
print(w)

print("\nHệ số đúng:")
print(correct)

print("\nSai số:")
print(w - correct)

print("\n===== YÊU CẦU 2 =====")

print("optimizer.zero_grad() : ")
print("mse.backward()       : ")
print("optimizer.step()     : ")

Initial coefficients:
tensor([[-0.4722],
        [-0.6487],
        [ 1.6973]], requires_grad=True)
Learned coefficients:
tensor([[0.9977],
        [1.9879],
        [3.1897]], requires_grad=True)

===== YÊU CẦU 1 =====
Hệ số học được:
tensor([[0.9977],
        [1.9879],
        [3.1897]], requires_grad=True)

Hệ số đúng:
tensor([[1.],
        [2.],
        [3.]])

Sai số:
tensor([[-0.0023],
        [-0.0121],
        [ 0.1897]], grad_fn=<SubBackward0>)

===== YÊU CẦU 2 =====
optimizer.zero_grad() : 
mse.backward()       : 
optimizer.step()     : 


BÀI 10

In [50]:
import random
import torch

A = torch.tensor(random.random(), requires_grad=True)
B = torch.tensor(random.random(), requires_grad=True)
C = torch.tensor(random.random(), requires_grad=True)
D = torch.tensor(random.random(), requires_grad=True)

EPOCHS = 2000
optimizer = torch.optim.NAdam(
    [A, B, C, D],
    lr=0.01
)
for _ in range(EPOCHS):

    y1 = A + B - 9
    y2 = C - D - 1
    y3 = A + C - 8
    y4 = B - D - 2

    
    sqerr = y1*y1 + y2*y2 + y3*y3 + y4*y4
    optimizer.zero_grad()
    sqerr.backward()
    optimizer.step()

print("A =", A)
print("B =", B)
print("C =", C)
print("D =", D)

print("\n===== YÊU CẦU 1 =====")

print("A + B =", A + B)
print("C - D =", C - D)
print("A + C =", A + C)
print("B - D =", B - D)

print("\nSai số:")

print("PT1:", A + B - 9)
print("PT2:", C - D - 1)
print("PT3:", A + C - 8)
print("PT4:", B - D - 2)

print("\n===== YÊU CẦU 2 =====")

print("Nghiệm tổng quát:")
print("A = t")
print("B = 9 - t")
print("C = 8 - t")
print("D = 7 - t")

A = tensor(4.7532, requires_grad=True)
B = tensor(4.2468, requires_grad=True)
C = tensor(3.2468, requires_grad=True)
D = tensor(2.2468, requires_grad=True)

===== YÊU CẦU 1 =====
A + B = tensor(8.9999, grad_fn=<AddBackward0>)
C - D = tensor(1.0000, grad_fn=<SubBackward0>)
A + C = tensor(8.0000, grad_fn=<AddBackward0>)
B - D = tensor(2.0000, grad_fn=<SubBackward0>)

Sai số:
PT1: tensor(-5.7220e-05, grad_fn=<SubBackward0>)
PT2: tensor(2.2173e-05, grad_fn=<SubBackward0>)
PT3: tensor(-1.9550e-05, grad_fn=<SubBackward0>)
PT4: tensor(-1.5020e-05, grad_fn=<SubBackward0>)

===== YÊU CẦU 2 =====
Nghiệm tổng quát:
A = t
B = 9 - t
C = 8 - t
D = 7 - t


BÀI 11

In [52]:
import torch
import numpy as np

X = torch.arange(1, 25)

print("Tensor X:")
print(X)

print("\nReshape 4 x 6:")
print(X.reshape(4, 6))

print("\nReshape 2 x 12:")
print(X.reshape(2, 12))

print("\nReshape 2 x 3 x 4:")
print(X.reshape(2, 3, 4))

A = torch.randn(3, 4)
B = torch.randn(3, 4)

print("\nTensor A:")
print(A)

print("\nTensor B:")
print(B)

print("\nA + B:")
print(A + B)

print("\nA * B:")
print(A * B)

print("\nA / B:")
print(A / B)

print("\nTrung bình theo cột:")
print(torch.mean(A, dim=0))

print("\nĐộ lệch chuẩn theo cột:")
print(torch.std(A, dim=0))

x = torch.tensor(2.0, requires_grad=True)

y = 2 * x**2 + 5 * x + 3

y.backward()

print("\n===== AUTOGRAD =====")
print("x =", x)
print("y =", y)
print("dy/dx =", x.grad)

polynomial = np.poly1d([2, -3, 5])

N = 20

X = np.random.randn(N, 1) * 5
Y = polynomial(X)

XX = np.hstack([
    X * X,
    X,
    np.ones_like(X)
])

w = torch.randn(3, 1, requires_grad=True)

x_train = torch.tensor(XX, dtype=torch.float32)
y_train = torch.tensor(Y, dtype=torch.float32)

optimizer = torch.optim.NAdam([w], lr=0.01)

for epoch in range(1000):
    optimizer.zero_grad()

    y_pred = x_train @ w

    mse = torch.mean(torch.square(y_train - y_pred))

    mse.backward()

    optimizer.step()

print("\n===== KẾT QUẢ HUẤN LUYỆN =====")
print("Các hệ số tìm được:")
print(w)

Tensor X:
tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24])

Reshape 4 x 6:
tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]])

Reshape 2 x 12:
tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

Reshape 2 x 3 x 4:
tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])

Tensor A:
tensor([[-1.0745,  1.0077, -0.6000, -0.4380],
        [-0.0196, -0.8406,  0.0059, -0.6419],
        [-1.1164,  0.5209, -0.4886, -0.0290]])

Tensor B:
tensor([[-0.8926, -0.4715, -0.6724, -0.1870],
        [-0.2028,  0.2248,  0.5926,  1.0331],
        [-0.5434, -0.4205, -0.8161,  0.2761]])

A + B:
tensor([[-1.9671,  0.5362, -1.2725, -0.6250],
        [-0.2224, -0.6158,  0.5986,  0.3912],
    